const KEY='projektNizzaDataV5';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const uid=()=>crypto.randomUUID?.()||Math.random().toString(36).slice(2);
const iso=(d=new Date())=>{const x=new Date(d);x.setMinutes(x.getMinutes()-x.getTimezoneOffset());return x.toISOString().slice(0,10)};
const parseDate=s=>new Date(s+'T12:00:00');
const addDays=(s,n)=>{const d=parseDate(s);d.setDate(d.getDate()+n);return iso(d)};
const fmt=s=>new Intl.DateTimeFormat('de-DE',{day:'2-digit',month:'2-digit',year:'numeric'}).format(parseDate(s));
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const roleLabel={gc:'Klassement',sprinter:'Sprinter',climber:'Bergfahrer',domestique:'Helfer'};
const typeLabel={endurance:'Grundlage',interval:'Intervalle',strength:'Kraft',long:'Lange Fahrt',luggage:'Mit Gepäck',rest:'Ruhetag',football:'Fußball',mobility:'Mobility'};
const defaults={
 profile:{name:'Sebastian',targetDate:'2027-07-25',monthlyKm:500,monthlyHm:6000,routeKm:1100},
 workouts:{},
 tours:[],
 route:[
  {name:'Haibach',country:'Deutschland',x:365,y:118,done:true},
  {name:'Wasserburg',country:'Deutschland',x:350,y:175,done:true},
  {name:'Schwaz',country:'Österreich',x:330,y:225,done:true},
  {name:'Kühtai',country:'Österreich',x:307,y:248,done:false},
  {name:'Landeck',country:'Österreich',x:286,y:245,done:false},
  {name:'Bormio',country:'Italien',x:279,y:291,done:false},
  {name:'Ligurien',country:'Italien',x:232,y:357,done:false},
  {name:'Nizza',country:'Frankreich',x:180,y:371,done:false}
 ],
 achievements:{xp:0,level:1},
 settings:{theme:'dark'}
};
function clone(x){return JSON.parse(JSON.stringify(x))}
function load(){try{const x=JSON.parse(localStorage.getItem(KEY));return x?deepMerge(clone(defaults),x):clone(defaults)}catch{return clone(defaults)}}
function deepMerge(a,b){for(const k in b){if(b[k]&&typeof b[k]==='object'&&!Array.isArray(b[k]))a[k]=deepMerge(a[k]||{},b[k]);else a[k]=b[k]}return a}
let data=load(),page='home',tourId=null,stageId=null,trainingMode='week',tourTab='overview',stageTab='result';
function save(msg){localStorage.setItem(KEY,JSON.stringify(data));render();if(msg)toast(msg)}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
function closeModal(){const m=$('#modal');if(m.open)m.close()}
function showModal(html){$('#modalBody').innerHTML=html;$('#modal').showModal()}
function daysUntil(){return Math.max(0,Math.ceil((parseDate(data.profile.targetDate)-new Date())/86400000))}
function workoutArray(){return Object.values(data.workouts).filter(Boolean)}
function doneWorkouts(){return workoutArray().filter(w=>w.done)}
function total(field){return doneWorkouts().reduce((s,w)=>s+(+w[field]||0),0)}
function monthKey(date=iso()){return date.slice(0,7)}
function monthTotals(key=monthKey()){const a=doneWorkouts().filter(w=>w.date.startsWith(key));return {km:a.reduce((s,w)=>s+(+w.km||0),0),hm:a.reduce((s,w)=>s+(+w.hm||0),0),min:a.reduce((s,w)=>s+(+w.actualDuration||+w.duration||0),0),count:a.length}}
function streak(){let n=0,d=iso();while(data.workouts[d]?.done){n++;d=addDays(d,-1)}return n}
function weekDates(center=iso()){const d=parseDate(center),day=(d.getDay()+6)%7;const start=addDays(iso(d),-day);return Array.from({length:7},(_,i)=>addDays(start,i))}
function workoutTypeClass(w){return 'type-'+(w?.type||'rest')}
function calcLevel(){const xp=doneWorkouts().reduce((s,w)=>s+25+(w.type==='long'?25:0)+(w.type==='luggage'?35:0),0);data.achievements.xp=xp;data.achievements.level=Math.floor(xp/500)+1;return data.achievements.level}
function render(){calcLevel();$$('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===page));({home:renderHome,training:renderTraining,map:renderMap,tours:renderTours,stats:renderStats}[page]||renderHome)()}
function renderHome(){const m=monthTotals(),pct=Math.min(100,m.km/data.profile.monthlyKm*100),w=data.workouts[iso()];$('#view').innerHTML=`
<section class="hero"><div class="overline">MISSION NIZZA 2027</div><h2>${daysUntil()} Tage<br>bis zum Neustart</h2><p>Du hast umgedreht. Jetzt baust du dich so auf, dass Kühtai beim nächsten Mal nicht das Ende, sondern erst der Anfang ist.</p><div class="hero-metrics"><div class="metric"><small>Diesen Monat</small><strong>${m.km.toFixed(0)} km</strong></div><div class="metric"><small>Höhenmeter</small><strong>${m.hm.toFixed(0)} hm</strong></div><div class="metric"><small>Serie</small><strong>${streak()} Tage</strong></div></div></section>
<section class="card"><div class="section-head"><div><h2>Heute</h2><p>${fmt(iso())} · maximal ein Haupttraining</p></div>${w?`<span class="pill ${w.done?'green':''}">${w.done?'Erledigt':'Geplant'}</span>`:''}</div>${w?workoutCard(w,true):`<div class="empty-state"><b>Noch kein Training geplant</b>Trage die Einheit ein, die wirklich zu deinem Tag passt.<div class="action-row" style="justify-content:center"><button class="btn" onclick="openWorkout('${iso()}')">Training anlegen</button></div></div>`}</section>
<section class="card"><div class="section-head"><div><h2>Monatsmission</h2><p>${new Intl.DateTimeFormat('de-DE',{month:'long',year:'numeric'}).format(new Date())}</p></div><button class="icon-btn" onclick="openGoals()">✎</button></div><div class="big-number">${m.km.toFixed(0)} <span style="font-size:1rem;color:var(--muted)">/ ${data.profile.monthlyKm} km</span></div><div class="progress"><span style="width:${pct}%"></span></div><div class="grid3" style="margin-top:13px"><div class="stat-card"><small>Einheiten</small><strong>${m.count}</strong></div><div class="stat-card"><small>Fahrzeit</small><strong>${Math.floor(m.min/60)}:${String(m.min%60).padStart(2,'0')} h</strong></div><div class="stat-card"><small>Zielstand</small><strong>${pct.toFixed(0)} %</strong></div></div></section>
<section class="card"><div class="section-head"><div><h2>Deine Woche</h2><p>Antippen, planen, ändern oder abschließen</p></div><button class="btn-secondary" onclick="goPage('training')">Öffnen</button></div>${weekStrip()}</section>`}
function workoutCard(w,large=false){return `<div class="today-workout ${workoutTypeClass(w)}"><span class="pill">${typeLabel[w.type]||w.type}</span><h3>${esc(w.title||'Training')}</h3><p>${esc(w.details||'Keine Beschreibung')} </p><div class="grid3" style="margin-top:13px"><div class="stat-card"><small>Geplant</small><strong>${w.duration||0} min</strong></div><div class="stat-card"><small>Distanz</small><strong>${w.km||0} km</strong></div><div class="stat-card"><small>Höhenmeter</small><strong>${w.hm||0} hm</strong></div></div><div class="action-row"><button class="btn" onclick="toggleWorkout('${w.date}')">${w.done?'Wieder öffnen':'Als erledigt markieren'}</button><button class="btn-secondary" onclick="openWorkout('${w.date}')">Bearbeiten</button><button class="btn-danger" onclick="deleteWorkout('${w.date}')">Löschen</button></div></div>`}
function weekStrip(){return `<div class="week-strip">${weekDates().map(d=>{const w=data.workouts[d],dow=new Intl.DateTimeFormat('de-DE',{weekday:'short'}).format(parseDate(d));return `<div class="day-card ${d===iso()?'today':''} ${w?.done?'done':''}" onclick="openWorkout('${d}')"><div class="dow">${dow}</div><div class="date">${d.slice(8,10)}.</div>${w?`<div class="workout-title">${esc(w.title)}</div><div class="workout-meta">${w.duration||0} min · ${w.done?'✓ erledigt':'geplant'}</div>`:`<div class="workout-title" style="color:var(--muted)">＋ Training</div>`}</div>`}).join('')}</div>`}
function renderTraining(){const tabs=`<div class="tabs"><button class="${trainingMode==='week'?'active':''}" onclick="setTrainingMode('week')">Woche</button><button class="${trainingMode==='month'?'active':''}" onclick="setTrainingMode('month')">Monat</button><button onclick="openWorkout('${iso()}')">＋ Einheit</button></div>`;$('#view').innerHTML=`<section class="card"><div class="section-head"><div><h2>Trainingsplan</h2><p>Jeder Tag hat höchstens ein Workout. Alles bleibt direkt editierbar.</p></div></div>${tabs}${trainingMode==='week'?renderWeekPlan():renderMonthPlan()}</section><section class="card"><div class="section-head"><div><h2>Plan-Regeln</h2><p>Kein starrer Automatismus</p></div></div><div class="grid2"><div class="stat-card"><small>1 Workout pro Tag</small><strong>Keine Dopplungen</strong></div><div class="stat-card"><small>Komplett flexibel</small><strong>Ändern · Verschieben · Löschen</strong></div></div></section>`}
function renderWeekPlan(){return `<div>${weekStrip()}</div><div style="margin-top:13px">${weekDates().map(d=>data.workouts[d]?`<div class="card flat">${workoutCard(data.workouts[d])}</div>`:'').join('')}</div>`}
function renderMonthPlan(){const now=new Date(),y=now.getFullYear(),m=now.getMonth(),first=new Date(y,m,1),last=new Date(y,m+1,0),offset=(first.getDay()+6)%7,cells=[];for(let i=0;i<offset;i++)cells.push(null);for(let d=1;d<=last.getDate();d++)cells.push(iso(new Date(y,m,d)));while(cells.length%7)cells.push(null);return `<div class="calendar">${['Mo','Di','Mi','Do','Fr','Sa','So'].map(x=>`<div class="cal-head">${x}</div>`).join('')}${cells.map(d=>{if(!d)return '<div class="cal-day empty"></div>';const w=data.workouts[d];return `<div class="cal-day ${d===iso()?'today':''} ${workoutTypeClass(w)}" onclick="openWorkout('${d}')"><div class="n">${+d.slice(8)}</div>${w?`<div class="cal-dot"></div><div class="cal-title">${esc(w.title)}</div>`:''}</div>`}).join('')}</div>`}
function renderMap(){const points=data.route.map(r=>`${r.x},${r.y}`).join(' ');$('#view').innerHTML=`<section class="card map-card"><div class="map-wrap"><svg class="europe-map" viewBox="0 0 560 460" role="img" aria-label="Europa-Karte mit Route nach Nizza"><defs><linearGradient id="routeGradient" x1="0" x2="1"><stop stop-color="#2e94ff"/><stop offset=".55" stop-color="#32dfd0"/><stop offset="1" stop-color="#ffd84d"/></linearGradient></defs><path class="land" d="M52 74L104 34l74 12 36 40 48-14 42 22 67-14 60 39-1 62-39 22-18 61-42 20-18 76-55 18-43-31-40 26-55-29-12-54-52-34-8-69 24-54z"/><path class="land" d="M341 266l41 24 11 63-29 67-34-11 17-55-26-48z"/><path class="land" d="M190 302l-26 58-41 19-31-29 28-57z"/><polyline class="route-line" points="${points}"/>${data.route.map((r,i)=>`<circle class="route-node" cx="${r.x}" cy="${r.y}" r="${i===0||i===data.route.length-1?8:6}" style="fill:${r.done?'#40da89':'#fff'}"/><text class="route-label" x="${r.x+10}" y="${r.y-9}">${esc(r.name)}</text>`).join('')}</svg><div class="map-overlay"><div class="section-head" style="margin:0"><div><h2>Europa-Route</h2><p>${data.route.filter(r=>r.done).length} von ${data.route.length} Schlüsselorten markiert</p></div><button class="btn-secondary" onclick="editRoute()">Route bearbeiten</button></div></div></div></section><section class="card"><div class="section-head"><div><h2>Meilensteine</h2><p>Tippe einen Ort an, um ihn als geschafft zu markieren.</p></div></div><div class="grid2">${data.route.map((r,i)=>`<button class="btn-secondary" onclick="toggleRoute(${i})" style="text-align:left"><b>${r.done?'✓ ':''}${esc(r.name)}</b><br><small style="color:var(--muted)">${esc(r.country)}</small></button>`).join('')}</div></section>`}
function renderTours(){if(tourId)return renderTourDetail();$('#view').innerHTML=`<section class="hero" style="min-height:210px"><div class="overline">DEIN EIGENES RENNKALENDER-ARCHIV</div><h2>Mehrere Touren.<br>Eine Karriere.</h2><p>Lege Tour de l’Ain, Trainingsrennen, Alpenrunden oder spätere Rundfahrten getrennt an. Jede Tour behält Teams, Etappen, Bilder und Wertungen.</p></section><section class="card"><div class="section-head"><div><h2>Meine Touren</h2><p>${data.tours.length} gespeichert</p></div><button class="btn" onclick="openTourForm()">＋ Neue Tour</button></div>${data.tours.length?`<div class="tour-grid">${data.tours.map(t=>`<article class="tour-card" onclick="openTour('${t.id}')"><span class="pill">${t.stages.length} Etappen</span><h3>${esc(t.name)}</h3><p>${esc(t.country||'Eigene Rundfahrt')} · ${t.teams.length} Teams</p></article>`).join('')}</div>`:`<div class="empty-state"><b>Noch keine Tour angelegt</b>Starte mit deiner Tour de l’Ain oder einer komplett neuen Rundfahrt.<div class="action-row" style="justify-content:center"><button class="btn" onclick="openTourForm()">Tour erstellen</button></div></div>`}</section>`}
function currentTour(){return data.tours.find(t=>t.id===tourId)}
function currentStage(){return currentTour()?.stages.find(s=>s.id===stageId)}
function renderTourDetail(){const t=currentTour();if(!t){tourId=null;return renderTours()}if(stageId)return renderStageDetail();const tabs=`<div class="tabs"><button class="${tourTab==='overview'?'active':''}" onclick="setTourTab('overview')">Übersicht</button><button class="${tourTab==='teams'?'active':''}" onclick="setTourTab('teams')">Teams</button><button class="${tourTab==='gc'?'active':''}" onclick="setTourTab('gc')">Gesamtklassement</button><button class="${tourTab==='mountain'?'active':''}" onclick="setTourTab('mountain')">Bergwertung</button><button class="${tourTab==='sprint'?'active':''}" onclick="setTourTab('sprint')">Sprintwertung</button></div>`;$('#view').innerHTML=`<section class="card"><div class="section-head"><div><button class="btn-secondary" onclick="backTours()">← Touren</button><h2 style="margin-top:13px">${esc(t.name)}</h2><p>${esc(t.country||'Eigene Rundfahrt')}</p></div><button class="icon-btn" onclick="openTourForm('${t.id}')">✎</button></div>${tabs}${renderTourTab(t)}</section>`}
function renderTourTab(t){
 if(tourTab==='overview'){
  const stages=t.stages.length
   ? t.stages.map((s,i)=>`<div class="stage-card" onclick="openStage('${s.id}')"><div class="stage-no">${i+1}</div><div style="flex:1"><h3>${esc(s.name)}</h3><p>${esc(s.start||'Start')} → ${esc(s.finish||'Ziel')} · ${s.km||0} km · ${s.hm||0} hm</p></div><span class="pill">${esc(s.type||'Etappe')}</span></div>`).join('')
   : `<div class="empty-state"><b>Noch keine Etappe</b>Lege Etappe 1 an und füge später dein Höhenprofil als Bild ein.</div>`;
  return `<div class="grid3"><div class="stat-card"><small>Etappen</small><strong>${t.stages.length}</strong></div><div class="stat-card"><small>Teams</small><strong>${t.teams.length}</strong></div><div class="stat-card"><small>Fahrer</small><strong>${t.teams.reduce((sum,x)=>sum+x.riders.length,0)}</strong></div></div><div class="section-head" style="margin-top:18px"><div><h2>Etappen</h2><p>Du erstellst jede Etappe selbst</p></div><button class="btn" onclick="openStageForm()">＋ Etappe</button></div>${stages}`;
 }
 if(tourTab==='teams'){
  const teams=t.teams.length?t.teams.map(teamCard).join(''):`<div class="empty-state"><b>Noch keine Teams</b>Erstelle Teams und ordne jedem Fahrer eine Rolle zu.</div>`;
  return `<div class="section-head"><div><h2>Teamübersicht</h2><p>Rollen sind farblich gekennzeichnet</p></div><button class="btn" onclick="openTeamForm()">＋ Team</button></div>${teams}`;
 }
 return classificationTable(totalClassification(t,tourTab),tourTab);
}

function teamCard(team){return `<div class="team-card" style="--team:${team.color||'#2e94ff'}"><div class="section-head" style="margin:0"><div><h3>${esc(team.name)}</h3><p>${team.riders.length} Fahrer</p></div><button class="icon-btn" onclick="event.stopPropagation();openTeamForm('${team.id}')">✎</button></div><div class="rider-grid">${team.riders.map(r=>`<div class="rider"><strong>${esc(r.name)}</strong><br><span class="role role-${r.role}">${roleLabel[r.role]||r.role}</span></div>`).join('')}</div></div>`}
function allRiders(t){return t.teams.flatMap(team=>team.riders.map(r=>({...r,teamId:team.id,teamName:team.name,teamColor:team.color||'#2e94ff'})))}
function totalClassification(t,type){const riders=allRiders(t),map={};riders.forEach(r=>map[r.id]={...r,time:0,points:0,stages:0});t.stages.forEach(s=>{if(type==='gc'){(s.results||[]).forEach(x=>{if(map[x.riderId]){map[x.riderId].time+=+x.seconds||0;map[x.riderId].stages++}})}else{const arr=type==='mountain'?s.mountain:s.sprint;(arr||[]).forEach(x=>{if(map[x.riderId])map[x.riderId].points+=+x.points||0})}});let arr=Object.values(map).filter(x=>type==='gc'?x.stages>0:x.points>0);arr.sort((a,b)=>type==='gc'?a.time-b.time:b.points-a.points);return arr}
function timeFmt(sec){sec=+sec||0;const h=Math.floor(sec/3600),m=Math.floor(sec%3600/60),s=sec%60;return `${h}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`}
function classificationTable(arr,type){return arr.length?`<table class="classification"><thead><tr><th>#</th><th>Fahrer</th><th>Team</th><th>${type==='gc'?'Zeit':'Punkte'}</th></tr></thead><tbody>${arr.map((r,i)=>`<tr><td class="pos">${i+1}</td><td><b>${esc(r.name)}</b><br><span class="role role-${r.role}">${roleLabel[r.role]}</span></td><td><span class="team-dot" style="background:${r.teamColor}"></span>${esc(r.teamName)}</td><td><b>${type==='gc'?timeFmt(r.time):r.points}</b></td></tr>`).join('')}</tbody></table>`:`<div class="empty-state"><b>Noch keine Wertung</b>Trage zunächst Ergebnisse in einer Etappe ein.</div>`}
async function renderStageDetail(){const t=currentTour(),s=currentStage();if(!s){stageId=null;return renderTourDetail()}const img=await getImage(s.imageKey);const tabs=`<div class="tabs"><button class="${stageTab==='result'?'active':''}" onclick="setStageTab('result')">Etappenergebnis</button><button class="${stageTab==='mountain'?'active':''}" onclick="setStageTab('mountain')">Bergwertung Tag</button><button class="${stageTab==='sprint'?'active':''}" onclick="setStageTab('sprint')">Sprintwertung Tag</button></div>`;$('#view').innerHTML=`<section class="card"><div class="section-head"><div><button class="btn-secondary" onclick="backTour()">← ${esc(t.name)}</button><h2 style="margin-top:13px">${esc(s.name)}</h2><p>${esc(s.start||'Start')} → ${esc(s.finish||'Ziel')} · ${s.km||0} km · ${s.hm||0} hm</p></div><button class="icon-btn" onclick="openStageForm('${s.id}')">✎</button></div>${img?`<img class="profile-image" src="${img}" alt="Etappenprofil">`:`<div class="empty-state"><b>Noch kein Höhenprofil</b>Füge ein Bild aus deiner Fotos- oder Dateien-App ein.<div class="action-row" style="justify-content:center"><button class="btn-secondary" onclick="chooseStageImage()">Bild hinzufügen</button></div></div>`}<div style="margin-top:14px">${tabs}${renderStageTab(t,s)}</div></section>`}
function renderStageTab(t,s){
 const arr=stageTab==='result'?(s.results||[]):stageTab==='mountain'?(s.mountain||[]):(s.sprint||[]);
 const riders=allRiders(t);
 const withData=arr.map(x=>({...x,...riders.find(r=>r.id===x.riderId)})).sort((a,b)=>(a.place||999)-(b.place||999));
 let body;
 if(withData.length){
  body=`<table class="classification"><thead><tr><th>#</th><th>Fahrer</th><th>Team</th><th>${stageTab==='result'?'Zeit':'Punkte'}</th><th></th></tr></thead><tbody>${withData.map((r,i)=>`<tr><td class="pos">${r.place||i+1}</td><td><b>${esc(r.name||'Unbekannt')}</b><br><span class="role role-${r.role}">${roleLabel[r.role]||''}</span></td><td><span class="team-dot" style="background:${r.teamColor}"></span>${esc(r.teamName||'')}</td><td><b>${stageTab==='result'?timeFmt(r.seconds):r.points}</b></td><td><button class="icon-btn" onclick="deleteStageRow('${r.riderId}')">×</button></td></tr>`).join('')}</tbody></table>`;
 }else{
  body=`<div class="empty-state"><b>Noch keine Fahrer eingetragen</b>Wähle Fahrer über ihre Team- und Rollenübersicht aus.</div>`;
 }
 const title=stageTab==='result'?'Etappenklassement':stageTab==='mountain'?'Bergwertung des Tages':'Sprintwertung des Tages';
 return `<div class="section-head"><div><h2>${title}</h2><p>Nur diese Etappe – Gesamtwertungen stehen eine Ebene höher.</p></div><button class="btn" onclick="openResultForm()">＋ Fahrer</button></div>${body}`;
}

function renderStats(){const m=monthTotals(),months=[];for(let i=5;i>=0;i--){const d=new Date();d.setMonth(d.getMonth()-i);const k=iso(d).slice(0,7);months.push({k,v:monthTotals(k).km})}const max=Math.max(1,...months.map(x=>x.v));$('#view').innerHTML=`<section class="hero" style="min-height:220px"><div class="overline">DEIN FORTSCHRITT</div><h2>Level ${data.achievements.level}</h2><p>${data.achievements.xp} XP gesammelt. Jede echte Einheit zählt – keine erfundenen Leistungsanalysen.</p><div class="progress" style="margin-top:20px"><span style="width:${data.achievements.xp%500/5}%"></span></div></section><section class="card"><div class="section-head"><div><h2>Motivierende Zahlen</h2><p>Nur Werte, die du selbst eingetragen hast</p></div></div><div class="grid4"><div class="stat-card"><small>Gesamt</small><strong>${total('km').toFixed(0)} km</strong></div><div class="stat-card"><small>Höhenmeter</small><strong>${total('hm').toFixed(0)} hm</strong></div><div class="stat-card"><small>Einheiten</small><strong>${doneWorkouts().length}</strong></div><div class="stat-card"><small>Mit Gepäck</small><strong>${doneWorkouts().filter(w=>w.luggage).reduce((s,w)=>s+(+w.km||0),0)} km</strong></div><div class="stat-card"><small>Längste Fahrt</small><strong>${Math.max(0,...doneWorkouts().map(w=>+w.km||0))} km</strong></div><div class="stat-card"><small>100-km-Fahrten</small><strong>${doneWorkouts().filter(w=>(+w.km||0)>=100).length}</strong></div><div class="stat-card"><small>Aktuelle Serie</small><strong>${streak()} Tage</strong></div><div class="stat-card"><small>Touren</small><strong>${data.tours.length}</strong></div></div></section><section class="card"><div class="section-head"><div><h2>6 Monate</h2><p>Kilometerentwicklung</p></div></div><div class="bar-chart">${months.map(x=>`<div class="bar-item"><div class="bar-fill" style="height:${Math.max(3,x.v/max*155)}px"></div><small>${x.k.slice(5)}</small></div>`).join('')}</div></section><section class="card"><div class="section-head"><div><h2>Daten & Sicherung</h2><p>Für GitHub Pages und Gerätewechsel</p></div></div><div class="action-row"><button class="btn-secondary" onclick="exportData()">Backup exportieren</button><button class="btn-secondary" onclick="$('#importFile').click()">Backup importieren</button><button class="btn-danger" onclick="resetData()">Alles zurücksetzen</button></div></section>`}
window.goPage=p=>{page=p;tourId=p==='tours'?tourId:null;stageId=null;render()};
$$('.bottom-nav button').forEach(b=>b.onclick=()=>{page=b.dataset.page;if(page!=='tours'){tourId=null;stageId=null}render()});
$('#quickAdd').onclick=()=>openWorkout(iso());
window.setTrainingMode=x=>{trainingMode=x;render()};window.setTourTab=x=>{tourTab=x;render()};window.setStageTab=x=>{stageTab=x;render()};
window.toggleWorkout=d=>{if(data.workouts[d]){data.workouts[d].done=!data.workouts[d].done;if(data.workouts[d].done&&!data.workouts[d].actualDuration)data.workouts[d].actualDuration=data.workouts[d].duration||0;save('Training aktualisiert')}};
window.deleteWorkout=d=>{if(confirm('Dieses Workout löschen?')){delete data.workouts[d];save('Workout gelöscht')}};
window.openWorkout=(date)=>{const w=data.workouts[date]||{date,type:'endurance',title:'',duration:60,actualDuration:0,km:0,hm:0,luggage:false,done:false,details:''};showModal(`<h2>${data.workouts[date]?'Workout bearbeiten':'Workout planen'}</h2><form id="workoutForm" class="form-grid"><div class="field"><label>Datum</label><input name="date" type="date" value="${w.date}" required></div><div class="field"><label>Art</label><select name="type">${Object.entries(typeLabel).map(([k,v])=>`<option value="${k}" ${w.type===k?'selected':''}>${v}</option>`).join('')}</select></div><div class="field full"><label>Titel</label><input name="title" value="${esc(w.title)}" placeholder="z. B. 2×20 min Sweetspot" required></div><div class="field"><label>Geplante Dauer (min)</label><input name="duration" type="number" value="${w.duration||0}"></div><div class="field"><label>Tatsächliche Dauer (min)</label><input name="actualDuration" type="number" value="${w.actualDuration||0}"></div><div class="field"><label>Kilometer</label><input name="km" type="number" step="0.1" value="${w.km||0}"></div><div class="field"><label>Höhenmeter</label><input name="hm" type="number" value="${w.hm||0}"></div><div class="field full"><label>Beschreibung / genauer Plan</label><textarea name="details" placeholder="Intervalle, Pausen, Herzfrequenzbereiche, Verpflegung …">${esc(w.details)}</textarea></div><div class="switchline"><span>Mit Gepäck</span><input name="luggage" type="checkbox" ${w.luggage?'checked':''}></div><div class="switchline"><span>Erledigt</span><input name="done" type="checkbox" ${w.done?'checked':''}></div><div class="field full"><button class="btn">Speichern</button></div></form>`);$('#workoutForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),newDate=f.get('date');if(newDate!==date)delete data.workouts[date];data.workouts[newDate]={date:newDate,type:f.get('type'),title:f.get('title'),duration:+f.get('duration')||0,actualDuration:+f.get('actualDuration')||0,km:+f.get('km')||0,hm:+f.get('hm')||0,luggage:f.get('luggage')==='on',done:f.get('done')==='on',details:f.get('details')||''};closeModal();save('Workout gespeichert')}};
window.openGoals=()=>{showModal(`<h2>Monatsziele</h2><form id="goalForm" class="form-grid"><div class="field"><label>Kilometer</label><input name="km" type="number" value="${data.profile.monthlyKm}"></div><div class="field"><label>Höhenmeter</label><input name="hm" type="number" value="${data.profile.monthlyHm}"></div><div class="field full"><label>Nizza-Zieldatum</label><input name="date" type="date" value="${data.profile.targetDate}"></div><div class="field full"><button class="btn">Speichern</button></div></form>`);$('#goalForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);data.profile.monthlyKm=+f.get('km');data.profile.monthlyHm=+f.get('hm');data.profile.targetDate=f.get('date');closeModal();save('Ziele gespeichert')}};
window.toggleRoute=i=>{data.route[i].done=!data.route[i].done;save('Route aktualisiert')};
window.editRoute=()=>{showModal(`<h2>Europa-Route bearbeiten</h2><form id="routeForm" class="form-grid"><div class="field full"><label>Orte – eine Zeile pro Ort, Format: Ort | Land</label><textarea name="route">${data.route.map(r=>`${r.name} | ${r.country}`).join('\n')}</textarea></div><div class="field full"><button class="btn">Speichern</button></div></form>`);$('#routeForm').onsubmit=e=>{e.preventDefault();const lines=new FormData(e.target).get('route').split('\n').map(x=>x.trim()).filter(Boolean);const old=data.route;data.route=lines.map((line,i)=>{const [name,country='']=line.split('|').map(x=>x.trim()),o=old.find(x=>x.name===name);const a=i/Math.max(1,lines.length-1);return {name,country,done:o?.done||false,x:365-185*a,y:118+253*a+Math.sin(a*Math.PI)*30}});closeModal();save('Route gespeichert')}};
window.openTour=id=>{tourId=id;tourTab='overview';render()};window.backTours=()=>{tourId=null;stageId=null;render()};window.backTour=()=>{stageId=null;render()};window.openStage=id=>{stageId=id;stageTab='result';render()};
window.openTourForm=(id)=>{const t=id?data.tours.find(x=>x.id===id):{name:'',country:'',description:'',teams:[],stages:[]};showModal(`<h2>${id?'Tour bearbeiten':'Neue Tour'}</h2><form id="tourForm" class="form-grid"><div class="field full"><label>Name</label><input name="name" value="${esc(t.name)}" placeholder="z. B. Tour de l’Ain" required></div><div class="field full"><label>Land / Region</label><input name="country" value="${esc(t.country||'')}"></div><div class="field full"><label>Beschreibung</label><textarea name="description">${esc(t.description||'')}</textarea></div><div class="field full"><button class="btn">Speichern</button></div></form>`);$('#tourForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);if(id){t.name=f.get('name');t.country=f.get('country');t.description=f.get('description')}else data.tours.push({id:uid(),name:f.get('name'),country:f.get('country'),description:f.get('description'),teams:[],stages:[]});closeModal();save('Tour gespeichert')}};
window.openTeamForm=(id)=>{const t=currentTour(),team=id?t.teams.find(x=>x.id===id):{id:uid(),name:'',color:'#2e94ff',riders:[]};showModal(`<h2>${id?'Team bearbeiten':'Team erstellen'}</h2><form id="teamForm" class="form-grid"><div class="field"><label>Teamname</label><input name="name" value="${esc(team.name)}" required></div><div class="field"><label>Teamfarbe</label><input name="color" type="color" value="${team.color||'#2e94ff'}"></div><div class="field full"><label>Fahrer – je Zeile: Name | Rolle</label><textarea name="riders" placeholder="Max Mustermann | gc\nTom Schnell | sprinter">${team.riders.map(r=>`${r.name} | ${r.role}`).join('\n')}</textarea><small style="color:var(--muted)">Rollen: gc, sprinter, climber, domestique</small></div><div class="field full"><button class="btn">Speichern</button></div></form>`);$('#teamForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),old=team.riders;team.name=f.get('name');team.color=f.get('color');team.riders=f.get('riders').split('\n').map(x=>x.trim()).filter(Boolean).map(line=>{const [name,role='domestique']=line.split('|').map(x=>x.trim());return {id:old.find(r=>r.name===name)?.id||uid(),name,role:['gc','sprinter','climber','domestique'].includes(role)?role:'domestique'}});if(!id)t.teams.push(team);closeModal();save('Team gespeichert')}};
window.openStageForm=(id)=>{const t=currentTour(),s=id?t.stages.find(x=>x.id===id):{id:uid(),name:`Etappe ${t.stages.length+1}`,start:'',finish:'',date:'',km:0,hm:0,type:'Hügel',results:[],mountain:[],sprint:[],imageKey:null};showModal(`<h2>${id?'Etappe bearbeiten':'Neue Etappe'}</h2><form id="stageForm" class="form-grid"><div class="field full"><label>Name</label><input name="name" value="${esc(s.name)}" required></div><div class="field"><label>Start</label><input name="start" value="${esc(s.start)}"></div><div class="field"><label>Ziel</label><input name="finish" value="${esc(s.finish)}"></div><div class="field"><label>Datum</label><input name="date" type="date" value="${s.date||''}"></div><div class="field"><label>Typ</label><select name="type">${['Sprint','Hügel','Berg','Zeitfahren'].map(x=>`<option ${s.type===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>Kilometer</label><input name="km" type="number" step="0.1" value="${s.km||0}"></div><div class="field"><label>Höhenmeter</label><input name="hm" type="number" value="${s.hm||0}"></div><div class="field full"><button class="btn">Speichern</button></div></form>`);$('#stageForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);Object.assign(s,{name:f.get('name'),start:f.get('start'),finish:f.get('finish'),date:f.get('date'),type:f.get('type'),km:+f.get('km')||0,hm:+f.get('hm')||0});if(!id)t.stages.push(s);closeModal();save('Etappe gespeichert')}};
window.openResultForm=()=>{const t=currentTour(),s=currentStage(),riders=allRiders(t);if(!riders.length)return alert('Lege zuerst Teams und Fahrer an.');const arr=stageTab==='result'?s.results:stageTab==='mountain'?s.mountain:s.sprint;showModal(`<h2>Fahrer eintragen</h2><form id="resultForm" class="form-grid"><div class="field full"><label>Fahrer</label><select name="rider">${t.teams.map(team=>`<optgroup label="${esc(team.name)}">${team.riders.map(r=>`<option value="${r.id}">${esc(r.name)} · ${roleLabel[r.role]}</option>`).join('')}</optgroup>`).join('')}</select></div><div class="field"><label>Platz</label><input name="place" type="number" value="${arr.length+1}"></div>${stageTab==='result'?`<div class="field"><label>Stunden</label><input name="h" type="number" value="3"></div><div class="field"><label>Minuten</label><input name="m" type="number" value="0"></div><div class="field"><label>Sekunden</label><input name="s" type="number" value="0"></div>`:`<div class="field"><label>Punkte</label><input name="points" type="number" value="10"></div>`}<div class="field full"><button class="btn">Speichern</button></div></form>`);$('#resultForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),riderId=f.get('rider');const existing=arr.find(x=>x.riderId===riderId),obj={riderId,place:+f.get('place')||arr.length+1};if(stageTab==='result')obj.seconds=(+f.get('h')||0)*3600+(+f.get('m')||0)*60+(+f.get('s')||0);else obj.points=+f.get('points')||0;if(existing)Object.assign(existing,obj);else arr.push(obj);closeModal();save('Wertung gespeichert')}};
window.deleteStageRow=riderId=>{const s=currentStage(),arr=stageTab==='result'?s.results:stageTab==='mountain'?s.mountain:s.sprint;s[stageTab==='result'?'results':stageTab]=arr.filter(x=>x.riderId!==riderId);save('Eintrag gelöscht')};
window.chooseStageImage=()=>{const inp=document.createElement('input');inp.type='file';inp.accept='image/*';inp.onchange=async()=>{const f=inp.files[0];if(!f)return;const key='stage-'+currentStage().id;await putImage(key,f);currentStage().imageKey=key;save('Etappenprofil gespeichert')};inp.click()};
function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open('ProjektNizzaImages',1);r.onupgradeneeded=()=>r.result.createObjectStore('images');r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function putImage(key,file){const db=await openDB();return new Promise((res,rej)=>{const tx=db.transaction('images','readwrite');tx.objectStore('images').put(file,key);tx.oncomplete=res;tx.onerror=()=>rej(tx.error)})}
async function getImage(key){if(!key)return null;try{const db=await openDB();const blob=await new Promise((res,rej)=>{const r=db.transaction('images').objectStore('images').get(key);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)});return blob?URL.createObjectURL(blob):null}catch{return null}}
window.exportData=()=>{const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`projekt-nizza-v5-backup-${iso()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
$('#importFile').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{data=deepMerge(clone(defaults),JSON.parse(r.result));save('Backup importiert')}catch{alert('Ungültige Datei')}};r.readAsText(f)};
window.resetData=()=>{if(confirm('Wirklich alle Trainings- und Tourdaten löschen?')){localStorage.removeItem(KEY);data=clone(defaults);save('App zurückgesetzt')}};
window.closeModal=closeModal;
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(()=>{}));
render();
