const KEY='nizza-v12-beta';
const OLD='nizza-v12-alpha';
const roleLabel={gc:'Gesamtfahrer',climber:'Bergfahrer',helper:'Helfer',sprinter:'Sprinter'};
const roleClass={gc:'role-gc',climber:'role-climber',helper:'role-helper',sprinter:'role-sprinter'};
const route=[
 {name:'Haibach',km:0,x:80,y:70},{name:'Wasserburg',km:132,x:150,y:135},{name:'Schwaz',km:264,x:235,y:200},{name:'Landeck',km:380,x:300,y:245},{name:'Bormio',km:515,x:338,y:325},{name:'Darfo',km:650,x:300,y:405},{name:'Novi Ligure',km:800,x:235,y:470},{name:'Finale Ligure',km:910,x:165,y:515},{name:'Isolabona',km:1030,x:100,y:550},{name:'Nizza',km:1100,x:50,y:580}
];
function base(){return {workouts:[],riders:[],tours:[],activeTourId:null}}
function load(){try{const n=JSON.parse(localStorage.getItem(KEY)||'null');if(n)return {...base(),...n};const o=JSON.parse(localStorage.getItem(OLD)||'null');if(o)return {...base(),workouts:o.workouts||[],riders:o.riders||[],tours:(o.tours||[]).map(t=>({...t,teams:[],stagesData:[]}))};}catch{}return base()}
let state=load(),view='start',trainingMode='week',anchor=new Date();
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],uid=()=>crypto.randomUUID?.()||Date.now()+Math.random().toString(16).slice(2),esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const iso=d=>{let x=new Date(d);x.setMinutes(x.getMinutes()-x.getTimezoneOffset());return x.toISOString().slice(0,10)},pd=s=>new Date(s+'T12:00:00'),fmt=d=>new Intl.DateTimeFormat('de-DE',{weekday:'long',day:'2-digit',month:'2-digit',year:'numeric'}).format(d);
function save(){localStorage.setItem(KEY,JSON.stringify(state));renderAll()}
function completed(){return state.workouts.filter(w=>w.done)}
function totals(){const a=completed();return {km:a.reduce((s,w)=>s+(+w.km||0),0),hm:a.reduce((s,w)=>s+(+w.hm||0),0),min:a.reduce((s,w)=>s+(+w.actual||+w.planned||0),0)}}
function progressKm(){const t=totals();return Math.min(1100,t.km*(0.55+Math.min(.45,(t.hm/10000)+(completed().length/50))))}
function bikerPos(k){for(let i=1;i<route.length;i++){if(k<=route[i].km){let a=route[i-1],b=route[i],q=(k-a.km)/(b.km-a.km);return{x:a.x+(b.x-a.x)*q,y:a.y+(b.y-a.y)*q}}}return route.at(-1)}
function nextPoint(k){return route.find(r=>r.km>k)||route.at(-1)}
function switchView(v){view=v;$$('.view').forEach(x=>x.classList.toggle('active',x.id===`view-${v}`));$$('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===v));window.scrollTo(0,0)}
$$('.bottom-nav button').forEach(b=>b.onclick=()=>switchView(b.dataset.view));$('#quickAdd').onclick=()=>view==='tours'?openTourForm():openWorkout();
function modal(html){$('#modalBody').innerHTML=html;$('#modal').showModal();$('#modalBody [data-close]')?.addEventListener('click',()=>$('#modal').close())}
function renderAll(){renderStart();renderTraining();renderMap();renderTours();renderStats()}
function renderStart(){const t=totals(),km=progressKm(),n=nextPoint(km),tour=activeTour();$('#view-start').innerHTML=`<article class="hero"><span class="eyebrow">MISSION NIZZA</span><h2>${km.toFixed(0)} virtuelle km</h2><p>Nächster Meilenstein: <b>${esc(n.name)}</b></p><div class="progressbar"><span style="width:${km/11}%"></span></div><div class="stat-grid"><div class="stat"><small>Echte km</small><strong>${t.km.toFixed(0)}</strong></div><div class="stat"><small>Höhenmeter</small><strong>${t.hm.toFixed(0)}</strong></div><div class="stat"><small>Touren</small><strong>${state.tours.length}</strong></div></div></article><article class="card"><div class="section-head"><h2>Aktive Tour</h2><button id="goTours" class="secondary">Öffnen</button></div>${tour?`<div class="big-link"><div><strong>${esc(tour.name)}</strong><span>${tour.teams?.length||0} Teams · ${tour.stagesData?.length||0} Etappen</span></div></div>`:'<div class="empty">Noch keine Tour erstellt.</div>'}</article>`;$('#goTours').onclick=()=>switchView('tours')}
function startWeek(d){let x=new Date(d);x.setDate(x.getDate()-((x.getDay()+6)%7));return x}function addDays(d,n){let x=new Date(d);x.setDate(x.getDate()+n);return x}function workoutOn(d){return state.workouts.find(w=>w.date===iso(d))}
function renderTraining(){
  let root=$('#view-training');
  root.innerHTML=`<div class="section-head"><div><span class="eyebrow">TRAINING</span><h2>Kalender</h2></div><button id="newWorkout" class="primary">+ Einheit</button></div><div class="tabbar"><button data-m="day" class="chip ${trainingMode==='day'?'active':''}">Tag</button><button data-m="week" class="chip ${trainingMode==='week'?'active':''}">Woche</button><button data-m="month" class="chip ${trainingMode==='month'?'active':''}">Monat</button></div><div class="period-nav"><button id="prev" class="secondary">‹</button><strong id="period"></strong><button id="next" class="secondary">›</button></div><div id="cal" class="calendar-list"></div>`;
  $('#newWorkout').onclick=()=>openWorkout();
  $$('[data-m]').forEach(b=>b.onclick=()=>{trainingMode=b.dataset.m;renderTraining()});
  $('#prev').onclick=()=>{anchor=addDays(anchor,trainingMode==='week'?-7:-1);renderTraining()};
  $('#next').onclick=()=>{anchor=addDays(anchor,trainingMode==='week'?7:1);renderTraining()};
  const c=$('#cal');
  if(trainingMode==='day'){
    c.append(dayCard(anchor)); $('#period').textContent=fmt(anchor);
  } else if(trainingMode==='week'){
    let s=startWeek(anchor); $('#period').textContent=`${s.toLocaleDateString('de-DE')} – ${addDays(s,6).toLocaleDateString('de-DE')}`;
    for(let i=0;i<7;i++) c.append(dayCard(addDays(s,i)));
  } else {
    let first=new Date(anchor.getFullYear(),anchor.getMonth(),1);
    $('#period').textContent=first.toLocaleDateString('de-DE',{month:'long',year:'numeric'});
    c.className='month-grid'; let s=startWeek(first);
    for(let i=0;i<42;i++){
      let d=addDays(s,i),w=workoutOn(d),el=document.createElement('button');
      el.className='month-cell';
      el.innerHTML=`<strong>${d.getDate()}</strong>${w?`<small>${esc(w.title)}</small>`:''}`;
      el.onclick=()=>openWorkout(w,d); c.append(el);
    }
  }
}
function dayCard(d){let w=workoutOn(d),e=document.createElement('article');e.className='day-card';e.innerHTML=`<div class="date">${fmt(d)}</div>${w?`<h3>${esc(w.title)}</h3><p>${esc(w.type||'Training')} · ${w.planned||0} Min.</p>`:'<h3>Noch kein Training</h3><p>Tippen zum Planen</p>'}`;e.onclick=()=>openWorkout(w,d);return e}
function openWorkout(w=null,d=new Date()){modal(`<div class="modal-head"><h2>Training</h2><button data-close class="icon-btn">×</button></div><form id="f"><label>Datum<input id="d" type="date" value="${w?.date||iso(d)}" required></label><label>Titel<input id="t" value="${esc(w?.title||'')}"></label><label>Art<input id="ty" value="${esc(w?.type||'Grundlage')}"></label><div class="grid2"><label>Geplant Min.<input id="pm" type="number" value="${w?.planned||0}"></label><label>Tatsächlich Min.<input id="am" type="number" value="${w?.actual||0}"></label></div><div class="grid2"><label>km<input id="km" type="number" step="0.1" value="${w?.km||0}"></label><label>hm<input id="hm" type="number" value="${w?.hm||0}"></label></div><label>Details<textarea id="de">${esc(w?.details||'')}</textarea></label><label class="check"><input id="done" type="checkbox" ${w?.done?'checked':''}> Erledigt</label><div class="actions">${w?'<button type="button" id="del" class="danger">Löschen</button>':''}<button class="primary">Speichern</button></div></form>`);$('#f').onsubmit=e=>{e.preventDefault();let item={id:w?.id||uid(),date:$('#d').value,title:$('#t').value,type:$('#ty').value,planned:+$('#pm').value,actual:+$('#am').value,km:+$('#km').value,hm:+$('#hm').value,details:$('#de').value,done:$('#done').checked};state.workouts=state.workouts.filter(x=>x.id===item.id||x.date!==item.date);let i=state.workouts.findIndex(x=>x.id===item.id);i>=0?state.workouts[i]=item:state.workouts.push(item);$('#modal').close();save()};$('#del')?.addEventListener('click',()=>{state.workouts=state.workouts.filter(x=>x.id!==w.id);$('#modal').close();save()})}
function renderMap(){let k=progressKm(),p=bikerPos(k),n=nextPoint(k),pts=route.map(r=>`${r.x},${r.y}`).join(' ');$('#view-map').innerHTML=`<div class="section-head"><div><span class="eyebrow">EUROPA-ROUTE</span><h2>Haibach → Nizza</h2></div></div><article class="card route-card"><svg viewBox="0 0 400 630" class="route-svg"><path class="country" d="M30 45 L220 25 L365 80 L350 210 L250 250 L170 220 L70 245 L25 150Z"/><path class="country" d="M190 210 L320 210 L350 300 L300 360 L215 335 L170 260Z"/><path class="country" d="M215 330 L305 350 L330 500 L275 590 L235 520 L250 430 L195 370Z"/><path class="country" d="M25 250 L175 220 L210 360 L170 500 L70 550 L20 430Z"/><polyline points="${pts}" class="route-line"/>${route.map(r=>`<circle cx="${r.x}" cy="${r.y}" r="5" class="route-dot"/><text x="${r.x+8}" y="${r.y-8}">${r.name}</text>`).join('')}<g transform="translate(${p.x},${p.y})"><circle r="16" class="bike-halo"/><text x="-10" y="7" class="bike">🚴</text></g></svg><div class="map-info"><strong>${k.toFixed(0)} / 1100 km</strong><span>Nächster Ort: ${esc(n.name)} · noch ${Math.max(0,n.km-k).toFixed(0)} km</span></div></article>`}
function activeTour(){return state.tours.find(t=>t.id===state.activeTourId)||state.tours[0]||null}
function renderTours(){let t=activeTour();$('#view-tours').innerHTML=`<div class="section-head"><div><span class="eyebrow">RUNDFAHRTEN</span><h2>Meine Touren</h2></div><button id="newTour" class="primary">+ Tour</button></div>${state.tours.length?`<div class="tour-select">${state.tours.map(x=>`<button data-tour="${x.id}" class="chip ${x.id===t?.id?'active':''}">${esc(x.name)}</button>`).join('')}</div>`:''}<div id="tourArea"></div>`;$('#newTour').onclick=()=>openTourForm();$$('[data-tour]').forEach(b=>b.onclick=()=>{state.activeTourId=b.dataset.tour;save()});let a=$('#tourArea');if(!t){a.innerHTML='<div class="empty">Erstelle deine erste Tour.</div>';return}a.innerHTML=`<article class="hero"><h2>${esc(t.name)}</h2><p>${esc(t.country||'')}</p><div class="actions"><button id="editTour" class="secondary">Bearbeiten</button><button id="addTeam" class="primary">+ Team</button><button id="addStage" class="primary">+ Etappe</button></div></article><div class="tabbar"><button data-tab="teams" class="chip active">Teams</button><button data-tab="stages" class="chip">Etappen</button><button data-tab="gc" class="chip">Gesamtklassement</button></div><div id="tourTab"></div>`;$('#editTour').onclick=()=>openTourForm(t);$('#addTeam').onclick=()=>openTeamForm(t);$('#addStage').onclick=()=>openStageForm(t);$$('[data-tab]').forEach(b=>b.onclick=()=>{b.parentElement.querySelectorAll('.chip').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderTourTab(t,b.dataset.tab)});renderTourTab(t,'teams')}
function openTourForm(t=null){modal(`<div class="modal-head"><h2>Tour</h2><button data-close class="icon-btn">×</button></div><form id="f"><label>Name<input id="n" value="${esc(t?.name||'')}"></label><label>Land<input id="c" value="${esc(t?.country||'')}"></label><div class="actions">${t?'<button type="button" id="del" class="danger">Löschen</button>':''}<button class="primary">Speichern</button></div></form>`);$('#f').onsubmit=e=>{e.preventDefault();let item=t?{...t}:{id:uid(),teams:[],stagesData:[]};item.name=$('#n').value;item.country=$('#c').value;if(t){state.tours[state.tours.findIndex(x=>x.id===t.id)]=item}else{state.tours.push(item);state.activeTourId=item.id}$('#modal').close();save()};$('#del')?.addEventListener('click',()=>{state.tours=state.tours.filter(x=>x.id!==t.id);state.activeTourId=state.tours[0]?.id||null;$('#modal').close();save()})}
function openTeamForm(t,team=null){modal(`<div class="modal-head"><h2>Team</h2><button data-close class="icon-btn">×</button></div><form id="f"><label>Name<input id="n" value="${esc(team?.name||'')}"></label><label>Teamfarbe<input id="co" type="color" value="${team?.color||'#2aa7ff'}"></label><div class="actions"><button class="primary">Speichern</button></div></form>`);$('#f').onsubmit=e=>{e.preventDefault();let x=team?{...team}:{id:uid(),riderIds:[]};x.name=$('#n').value;x.color=$('#co').value;if(team)t.teams[t.teams.findIndex(a=>a.id===team.id)]=x;else t.teams.push(x);$('#modal').close();save()}}
function openRiderForm(t,team,r=null){modal(`<div class="modal-head"><h2>Fahrer</h2><button data-close class="icon-btn">×</button></div><form id="f"><label>Name<input id="n" value="${esc(r?.name||'')}"></label><label>Rolle<select id="ro">${Object.entries(roleLabel).map(([k,v])=>`<option value="${k}" ${r?.role===k?'selected':''}>${v}</option>`).join('')}</select></label><label>Nationalität<input id="na" value="${esc(r?.nation||'')}"></label><div class="actions">${r?'<button type="button" id="del" class="danger">Löschen</button>':''}<button class="primary">Speichern</button></div></form>`);$('#f').onsubmit=e=>{e.preventDefault();let x=r?{...r}:{id:uid()};x.name=$('#n').value;x.role=$('#ro').value;x.nation=$('#na').value;let i=state.riders.findIndex(a=>a.id===x.id);i>=0?state.riders[i]=x:state.riders.push(x);if(!team.riderIds.includes(x.id))team.riderIds.push(x.id);$('#modal').close();save()};$('#del')?.addEventListener('click',()=>{team.riderIds=team.riderIds.filter(id=>id!==r.id);state.riders=state.riders.filter(x=>x.id!==r.id);$('#modal').close();save()})}
function openStageForm(t,s=null){modal(`<div class="modal-head"><h2>Etappe</h2><button data-close class="icon-btn">×</button></div><form id="f"><label>Name<input id="n" value="${esc(s?.name||'Etappe '+((t.stagesData?.length||0)+1))}"></label><label>Datum<input id="d" type="date" value="${s?.date||iso(new Date())}"></label><div class="actions"><button class="primary">Speichern</button></div></form>`);$('#f').onsubmit=e=>{e.preventDefault();let x=s?{...s}:{id:uid(),results:[],mountain:[]};x.name=$('#n').value;x.date=$('#d').value;t.stagesData=t.stagesData||[];let i=t.stagesData.findIndex(a=>a.id===x.id);i>=0?t.stagesData[i]=x:t.stagesData.push(x);$('#modal').close();save()}}
function renderTourTab(t,tab){let root=$('#tourTab');if(tab==='teams'){root.innerHTML=(t.teams||[]).map(team=>`<article class="team-card" style="--team:${team.color}"><div class="section-head"><h3>${esc(team.name)}</h3><button data-add-rider="${team.id}" class="secondary">+ Fahrer</button></div><div class="rider-grid">${team.riderIds.map(id=>state.riders.find(r=>r.id===id)).filter(Boolean).map(r=>`<button class="rider-stone ${roleClass[r.role]}" data-rider="${r.id}" data-team="${team.id}"><strong>${esc(r.name)}</strong><span>${roleLabel[r.role]} · ${esc(r.nation||'')}</span></button>`).join('')||'<p class="muted">Noch keine Fahrer.</p>'}</div></article>`).join('')||'<div class="empty">Noch keine Teams.</div>';$$('[data-add-rider]').forEach(b=>b.onclick=()=>openRiderForm(t,t.teams.find(x=>x.id===b.dataset.addRider)));$$('[data-rider]').forEach(b=>{let team=t.teams.find(x=>x.id===b.dataset.team),r=state.riders.find(x=>x.id===b.dataset.rider);b.onclick=()=>openRiderForm(t,team,r)})}else if(tab==='stages'){root.innerHTML=(t.stagesData||[]).map(s=>`<article class="stage-card"><div><strong>${esc(s.name)}</strong><span>${s.date?pd(s.date).toLocaleDateString('de-DE'):''}</span></div><button data-stage="${s.id}" class="primary">Klassements</button></article>`).join('')||'<div class="empty">Noch keine Etappen.</div>';$$('[data-stage]').forEach(b=>b.onclick=()=>openClassifications(t,t.stagesData.find(x=>x.id===b.dataset.stage)))}else{renderOverallGC(t,root)}}
function allTourRiders(t){return [...new Set((t.teams||[]).flatMap(x=>x.riderIds))].map(id=>state.riders.find(r=>r.id===id)).filter(Boolean)}
function openClassifications(t,s){const riders=allTourRiders(t);modal(`<div class="modal-head"><h2>${esc(s.name)}</h2><button data-close class="icon-btn">×</button></div><div class="tabbar"><button data-c="stage" class="chip active">Etappensieger</button><button data-c="mountain" class="chip">Bergwertung</button><button data-c="gc" class="chip">Gesamt nach Etappe</button></div><div id="cls"></div>`);function draw(kind){const list=kind==='stage'?s.results:(kind==='mountain'?s.mountain:(s.gc||[]));$('#cls').innerHTML=`<div class="classification-list">${list.map((x,i)=>{let r=state.riders.find(a=>a.id===x.riderId);return `<div class="class-row"><b>${i+1}</b><span>${esc(r?.name||'Unbekannt')}</span><button data-rem="${i}" class="danger">×</button></div>`}).join('')}</div><button id="addCls" class="primary">+ Fahrer hinzufügen</button>`;$('#addCls').onclick=()=>chooseRider(riders,rid=>{let arr=kind==='stage'?s.results:(kind==='mountain'?s.mountain:(s.gc=s.gc||[]));arr.push({riderId:rid});save();openClassifications(t,s)});$$('[data-rem]').forEach(b=>b.onclick=()=>{list.splice(+b.dataset.rem,1);save();openClassifications(t,s)})}$$('[data-c]').forEach(b=>b.onclick=()=>{$$('[data-c]').forEach(x=>x.classList.remove('active'));b.classList.add('active');draw(b.dataset.c)});draw('stage')}
function chooseRider(riders,cb){modal(`<div class="modal-head"><h2>Fahrer auswählen</h2><button data-close class="icon-btn">×</button></div><div class="rider-grid">${riders.map(r=>`<button data-pick="${r.id}" class="rider-stone ${roleClass[r.role]}"><strong>${esc(r.name)}</strong><span>${roleLabel[r.role]}</span></button>`).join('')}</div>`);$$('[data-pick]').forEach(b=>b.onclick=()=>{let id=b.dataset.pick;$('#modal').close();cb(id)})}
function renderOverallGC(t,root){let stages=t.stagesData||[],last=[...stages].reverse().find(s=>s.gc?.length);root.innerHTML=last?`<article class="card"><h3>Gesamtklassement nach ${esc(last.name)}</h3>${last.gc.map((x,i)=>{let r=state.riders.find(a=>a.id===x.riderId);return `<div class="class-row"><b>${i+1}</b><span>${esc(r?.name||'')}</span></div>`}).join('')}</article>`:'<div class="empty">Noch kein Gesamtklassement gespeichert.</div>'}
function renderStats(){let t=totals();$('#view-stats').innerHTML=`<div class="section-head"><div><span class="eyebrow">STATISTIK</span><h2>Fortschritt</h2></div></div><div class="stat-grid"><div class="stat"><small>Kilometer</small><strong>${t.km.toFixed(0)}</strong></div><div class="stat"><small>Höhenmeter</small><strong>${t.hm.toFixed(0)}</strong></div><div class="stat"><small>Fahrzeit</small><strong>${Math.floor(t.min/60)} h</strong></div></div>`}
renderAll();if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js').catch(()=>{});
