const VERSION='12.0';
const KEY='projektNizzaDataV12';
const DB='ProjektNizzaDB', STORE='state', DBKEY='main';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const uid=()=>crypto.randomUUID?.()||Math.random().toString(36).slice(2);
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const iso=d=>new Date(d).toISOString().slice(0,10);
const fmt=d=>new Intl.DateTimeFormat('de-DE',{weekday:'short',day:'2-digit',month:'2-digit',year:'numeric'}).format(new Date(d+'T12:00:00'));
const addDays=(d,n)=>{const x=new Date(d+'T12:00:00');x.setDate(x.getDate()+n);return iso(x)};
const monday=d=>{const x=new Date(d+'T12:00:00'),day=(x.getDay()+6)%7;x.setDate(x.getDate()-day);return iso(x)};
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const ROUTE=[['Haibach',0],['Wasserburg',125],['Schwaz',250],['Landeck',330],['Bormio',470],['Darfo Boario Terme',600],['Monteleone',710],['Novi Ligure',825],['Finale Ligure',930],['Isolabona',1030],['Nizza',1100]];
const roleLabel={gc:'Klassement',berg:'Bergfahrer',sprinter:'Sprinter',helfer:'Helfer',jaeger:'Etappenjäger'};
let view='home', trainingMode='week', weekStart=monday(iso(new Date())), monthCursor=iso(new Date()).slice(0,7), data;

function blank(){return {version:12,profile:{targetDate:'2027-07-26',monthlyGoal:500,lastBackup:null},plan:[],riderPool:[],tours:[],activeTourId:null,notifiedStops:[]}}
function normalize(x){const b=blank(),d={...b,...(x||{}),profile:{...b.profile,...(x?.profile||{})}};d.plan=(d.plan||[]).map(p=>({...p,id:p.id||uid(),date:p.date||iso(new Date()),done:!!p.done,actual:p.actual||{km:0,hm:0,duration:0,rpe:5,gear:false,note:''}}));d.riderPool=d.riderPool||[];d.tours=d.tours||[];return d}
function migrate(){for(const k of [KEY,'projektNizzaDataV11','projektNizzaDataV8','projektNizzaDataV7','projektNizzaDataV6','projektNizzaDataV4']){try{const v=JSON.parse(localStorage.getItem(k)||'null');if(v)return normalize(v)}catch{}}return blank()}
function openDB(){return new Promise((res,rej)=>{const q=indexedDB.open(DB,1);q.onupgradeneeded=()=>{if(!q.result.objectStoreNames.contains(STORE))q.result.createObjectStore(STORE)};q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error)})}
async function dbGet(){try{const db=await openDB();return await new Promise((res,rej)=>{const q=db.transaction(STORE).objectStore(STORE).get(DBKEY);q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error)})}catch{return null}}
async function dbPut(){try{const db=await openDB();db.transaction(STORE,'readwrite').objectStore(STORE).put(data,DBKEY)}catch{}}
function snapshot(){try{const arr=JSON.parse(localStorage.getItem('projektNizzaSnapshots')||'[]');arr.unshift({at:new Date().toISOString(),data});localStorage.setItem('projektNizzaSnapshots',JSON.stringify(arr.slice(0,8)))}catch{}}
function save(msg){snapshot();data.version=12;localStorage.setItem(KEY,JSON.stringify(data));dbPut();render();if(msg)toast(msg)}
function toast(t){const e=document.createElement('div');e.className='toast';e.textContent=t;document.body.append(e);setTimeout(()=>e.remove(),1800)}
function activeTour(){return data.tours.find(t=>t.id===data.activeTourId)||data.tours[0]}

function trainingImpact(){let km=0,hm=0,days=[],rpe=0,count=0;for(const p of data.plan.filter(x=>x.done)){const a=p.actual||{};if(['Grundlage','Sweetspot','Bergtraining','Lange Fahrt','Regeneration','Rennrad'].includes(p.type)||a.km>0){km+=+a.km||0;hm+=+a.hm||0;rpe+=+a.rpe||5;count++;days.push(p.date)}}days=[...new Set(days)].sort();let consecutive=0,maxCon=0;for(let i=0;i<days.length;i++){if(i&&addDays(days[i-1],1)===days[i])consecutive++;else consecutive=1;maxCon=Math.max(maxCon,consecutive)}const avgRpe=count?rpe/count:0;const endurance=clamp(Math.round(km/12+days.length*1.5),0,100);const climbing=clamp(Math.round(hm/180+Math.min(km/35,20)),0,100);const resilience=clamp(Math.round(count*4+avgRpe*3+hm/500),0,100);const multi=clamp(Math.round(maxCon*13+days.length*1.5),0,100);const recent=data.plan.filter(p=>p.done&&p.date>=addDays(iso(new Date()),-4)).length;const recovery=clamp(88-recent*10-Math.max(0,avgRpe-6)*6,15,100);const quality=.30*endurance+.25*climbing+.20*resilience+.15*multi+.10*recovery;const virtual=clamp(km*(.28+.0065*quality)+hm/1000*10,0,1100);return {km,hm,endurance,climbing,resilience,multi,recovery,quality,virtual}}

function shell(body){return `<div class="app"><header class="topbar"><div class="eyebrow">DEINE RADSPORT-KARRIERE</div><div class="title">Projekt Nizza <b>${VERSION}</b></div></header><main class="content">${body}</main>${nav()}</div>`}
function nav(){const items=[['home','⌂','Start'],['training','▦','Training'],['journey','◎','Reise'],['tours','♛','Touren'],['more','•••','Mehr']];return `<nav class="nav">${items.map(([v,i,l])=>`<button data-view="${v}" class="${view===v?'active':''}"><span class="ico">${i}</span>${l}</button>`).join('')}</nav>`}
function render(){let b=view==='home'?home():view==='training'?training():view==='journey'?journey():view==='tours'?tours():more();$('#app').innerHTML=shell(b);bind()}

function home(){const f=trainingImpact(),today=iso(new Date()),p=data.plan.find(x=>x.date===today);const month=data.plan.filter(x=>x.done&&x.date.slice(0,7)===today.slice(0,7));const mk=month.reduce((s,x)=>s+(+x.actual?.km||0),0);return `<section class="card hero"><div class="eyebrow">NÄCHSTER VERSUCH</div><h1>${Math.max(0,Math.ceil((new Date(data.profile.targetDate)-new Date())/86400000))} Tage<br>bis zum Neustart</h1><p>Du baust die Form auf, mit der Kühtai beim nächsten Mal nicht das Ende ist.</p><div class="grid3"><div class="stat"><small>Diesen Monat</small><strong>${mk.toFixed(0)} km</strong></div><div class="stat"><small>Kletterform</small><strong>${f.climbing}%</strong></div><div class="stat"><small>Gesamtform</small><strong>${Math.round(f.quality)}%</strong></div></div></section><section class="card"><div class="section-head"><h2>Heute</h2><button class="btn secondary" data-go-training>Öffnen</button></div>${p?dayCard(p,true):`<div class="empty"><b>Noch kein Training geplant</b><p>Lege für heute eine Einheit an.</p><button class="btn" data-add-training data-date="${today}">Training anlegen</button></div>`}</section><section class="card"><div class="section-head"><h2>Nizza-Reise</h2><button class="btn secondary" data-view="journey">Ansehen</button></div><div class="grid3"><div class="stat"><small>Virtuell</small><strong>${f.virtual.toFixed(0)} km</strong></div><div class="stat"><small>Echt gefahren</small><strong>${f.km.toFixed(0)} km</strong></div><div class="stat"><small>Höhenmeter</small><strong>${f.hm.toFixed(0)}</strong></div></div></section>`}

function training(){const title=trainingMode==='month'?new Intl.DateTimeFormat('de-DE',{month:'long',year:'numeric'}).format(new Date(monthCursor+'-01')):'Trainingsübersicht';return `<section class="card"><div class="section-head"><div><div class="eyebrow">DEIN TRAININGSPLAN</div><h2>${title}</h2></div><button class="btn" data-add-training>+ Einheit</button></div><div class="seg"><button data-mode="day" class="${trainingMode==='day'?'active':''}">Tag</button><button data-mode="week" class="${trainingMode==='week'?'active':''}">Woche</button><button data-mode="month" class="${trainingMode==='month'?'active':''}">Monat</button></div>${trainingMode==='day'?dayView():trainingMode==='week'?weekView():monthView()}</section>`}
function dayView(){const d=iso(new Date());const p=data.plan.find(x=>x.date===d);return `<div class="datebar"><button data-shift-day="-1">‹</button><strong>${fmt(d)}</strong><button data-shift-day="1">›</button></div>${p?dayCard(p):`<div class="empty">Kein Training an diesem Tag.<br><br><button class="btn" data-add-training data-date="${d}">Einheit anlegen</button></div>`}`}
function weekView(){const days=Array.from({length:7},(_,i)=>addDays(weekStart,i));return `<div class="datebar"><button data-shift-week="-7">‹</button><strong>${fmt(days[0])} – ${fmt(days[6])}</strong><button data-shift-week="7">›</button></div>${days.map(d=>{const p=data.plan.find(x=>x.date===d);return p?dayCard(p):`<div class="day-card"><div class="summary"><div class="datebox"><small>${new Intl.DateTimeFormat('de-DE',{weekday:'short'}).format(new Date(d+'T12:00:00'))}</small><b>${d.slice(8)}</b></div><div><h3>Kein Training</h3><span class="muted">${fmt(d)}</span></div><button class="icon-btn" data-add-training data-date="${d}">＋</button></div></div>`}).join('')}</div>`}
function monthView(){const [y,m]=monthCursor.split('-').map(Number),first=new Date(y,m-1,1),last=new Date(y,m,0),offset=(first.getDay()+6)%7,cells=[];for(let i=0;i<offset;i++)cells.push('');for(let d=1;d<=last.getDate();d++)cells.push(`${monthCursor}-${String(d).padStart(2,'0')}`);return `<div class="datebar"><button data-shift-month="-1">‹</button><strong>${new Intl.DateTimeFormat('de-DE',{month:'long',year:'numeric'}).format(first)}</strong><button data-shift-month="1">›</button></div><div class="month-grid">${['Mo','Di','Mi','Do','Fr','Sa','So'].map(x=>`<b>${x}</b>`).join('')}${cells.map(d=>{if(!d)return'<div></div>';const p=data.plan.find(x=>x.date===d);return `<button class="mday ${p?'has':''} ${d===iso(new Date())?'today':''}" data-month-day="${d}"><b>${+d.slice(8)}</b>${p?`<div>${esc(p.title).slice(0,18)}</div>`:''}</button>`}).join('')}</div>`}
function dayCard(p,compact=false){return `<article class="day-card" data-card="${p.id}"><div class="summary" data-toggle-card="${p.id}"><div class="datebox"><small>${new Intl.DateTimeFormat('de-DE',{weekday:'short'}).format(new Date(p.date+'T12:00:00'))}</small><b>${p.date.slice(8)}</b></div><div><span class="tag">${esc(p.type||'Training')}</span><h3>${esc(p.title)}</h3><div class="muted">${fmt(p.date)} · ${p.duration||0} Min · ${esc(p.zone||'–')}</div></div><div>${p.done?'✓':'›'}</div></div>${compact?'':`<div class="detail"><p>${esc(p.details||'Keine Details eingetragen.')}</p>${p.done?`<p><b>Erledigt:</b> ${p.actual?.km||0} km · ${p.actual?.hm||0} hm · RPE ${p.actual?.rpe||'-'}</p>`:''}<div class="day-actions"><button class="icon-btn" data-complete="${p.id}">${p.done?'Ergebnis ändern':'Durchführen'}</button><button class="icon-btn" data-edit-training="${p.id}">Bearbeiten</button><button class="icon-btn" data-delete-training="${p.id}">Löschen</button></div></div>`}</article>`}

function journey(){const f=trainingImpact(),next=ROUTE.find(x=>x[1]>f.virtual)||ROUTE.at(-1),idx=Math.max(0,ROUTE.findIndex(x=>x[1]>f.virtual)-1),segStart=ROUTE[idx]||ROUTE[0],segEnd=ROUTE[idx+1]||ROUTE.at(-1),segPct=segEnd[1]===segStart[1]?100:clamp((f.virtual-segStart[1])/(segEnd[1]-segStart[1])*100,0,100);const totalHeight=(f.virtual/1100)*((ROUTE.length-1)*88);return `<section class="card"><div class="section-head"><div><div class="eyebrow">DEINE VIRTUELLE REISE</div><h2>${f.virtual.toFixed(0)} / 1.100 km</h2></div></div><p class="muted">Die Position hängt von gefahrenen Kilometern, Höhenmetern und deiner Form ab. Gute Kletter- und Mehrtagesform machen dein Training auf der Reise wirksamer.</p><div class="route-wrap"><div class="route-line"></div><div class="route-progress" style="height:${totalHeight}px"></div><div class="cyclist" style="top:${30+totalHeight}px">🚴</div>${ROUTE.map(([name,km],i)=>`<div class="stop ${f.virtual>=km?'done':''} ${i===idx+1?'current':''}"><div class="dot"></div><div class="stop-box"><b>${name}</b><div class="muted">${km} km ${f.virtual>=km?'· erreicht':''}</div></div></div>`).join('')}</div></section><section class="card"><h2>Aktueller Abschnitt</h2><p><b>${segStart[0]} → ${segEnd[0]}</b></p><div class="meter"><i style="width:${segPct}%"></i></div><p class="muted">Noch ${Math.max(0,next[1]-f.virtual).toFixed(0)} virtuelle Kilometer bis ${next[0]}.</p></section><section class="card"><h2>Deine Form</h2><div class="form-grid">${[['Ausdauer',f.endurance],['Kletterform',f.climbing],['Belastbarkeit',f.resilience],['Mehrtagesform',f.multi],['Regeneration',f.recovery],['Gesamtform',Math.round(f.quality)]].map(([n,v])=>`<div class="form-meter"><b>${n}</b><span style="float:right">${v}%</span><div class="meter"><i style="width:${v}%"></i></div></div>`).join('')}</div></section>`}

function tours(){
 const t=activeTour();
 let tabs=data.tours.length?'<div class="tour-tabs">'+data.tours.map(x=>'<button class="icon-btn" data-select-tour="'+x.id+'">'+esc(x.name)+'</button>').join('')+'</div>':'';
 return '<section class="card"><div class="section-head"><div><div class="eyebrow">DEINE RUNDFAHRTEN</div><h2>'+(t?esc(t.name):'Noch keine Tour')+'</h2></div><button class="btn" data-new-tour>+ Tour</button></div>'+tabs+(t?tourDetail(t):'<div class="empty">Erstelle deine erste Tour.</div>')+'</section>';
}
function tourDetail(t){
 const riders=(t.riderIds||[]).map(id=>data.riderPool.find(r=>r.id===id)).filter(Boolean);
 const cards=riders.length?'<div class="rider-grid">'+riders.map(riderCard).join('')+'</div>':'<div class="empty">Noch keine Fahrer zugeordnet.</div>';
 return '<div class="seg"><button class="active" data-tour-section="riders">Fahrer</button><button data-tour-section="stages">Etappen</button><button data-tour-section="standings">Klassement</button></div><div id="tourSection"><div class="section-head"><h2>Fahrerpool der Tour</h2><button class="btn secondary" data-add-rider>+ Fahrer</button></div>'+cards+'<div class="day-actions"><button class="btn secondary" data-manage-pool>Globalen Fahrerpool öffnen</button><button class="btn secondary" data-new-stage>Etappe erstellen</button></div></div>';
}
function riderCard(r){return '<div class="rider"><span class="role '+r.role+'">'+(roleLabel[r.role]||r.role)+'</span><h4>'+esc(r.name)+'</h4><small>'+esc(r.nation||'')+' · Stärke '+(r.overall||70)+'</small><div class="day-actions"><button class="icon-btn" data-edit-rider="'+r.id+'">Bearbeiten</button><button class="icon-btn" data-remove-rider="'+r.id+'">Aus Tour</button></div></div>'}
function stageSection(t){
 const stages=t.stages||[];
 return '<div class="section-head"><h2>Etappen</h2><button class="btn" data-new-stage>+ Etappe</button></div>'+(stages.length?stages.map(s=>'<div class="stage"><b>Etappe '+s.number+': '+esc(s.start)+' → '+esc(s.finish)+'</b><p class="muted">'+(s.km||0)+' km · '+(s.hm||0)+' hm · '+esc(s.type||'')+'</p><div class="day-actions"><button class="icon-btn" data-stage-result="'+s.id+'">Ergebnis</button><button class="icon-btn" data-delete-stage="'+s.id+'">Löschen</button></div></div>').join(''):'<div class="empty">Noch keine Etappen.</div>');
}
function standings(t){
 const rows=[];
 (t.stages||[]).forEach(s=>(s.results||[]).forEach(x=>{
  let r=rows.find(y=>y.riderId===x.riderId);
  if(!r){r={riderId:x.riderId,time:0,sprint:0,mountain:0};rows.push(r)}
  r.time+=(+x.seconds||0);r.sprint+=(+x.sprint||0);r.mountain+=(+x.mountain||0);
 }));
 rows.sort((a,b)=>a.time-b.time);
 if(!rows.length)return '<h2>Gesamtklassement</h2><div class="empty">Noch keine Ergebnisse.</div>';
 let html='<h2>Gesamtklassement</h2>';
 rows.forEach((x,i)=>{const r=data.riderPool.find(y=>y.id===x.riderId);const gap=i?('+'+(x.time-rows[0].time)+' s'):'Leader';html+='<div class="stage"><b>'+(i+1)+'. '+esc(r?r.name:'Fahrer')+'</b><span style="float:right">'+gap+'</span><p class="muted">Sprint '+x.sprint+' · Berg '+x.mountain+'</p></div>'});
 return html;
}


function more(){return `<section class="card"><h2>Datensicherheit</h2><p class="muted">Deine Daten werden gleichzeitig in IndexedDB und lokal gespeichert. Erstelle trotzdem regelmäßig ein Backup.</p><div class="backup-actions"><button class="btn" data-export>Backup exportieren</button><button class="btn secondary" data-import>Backup importieren</button><button class="btn secondary" data-restore>Letzten lokalen Snapshot wiederherstellen</button></div></section><section class="card"><h2>Einstellungen</h2><div class="field"><label>Monatsziel Kilometer</label><input id="monthlyGoal" type="number" value="${data.profile.monthlyGoal||500}"></div><button class="btn" data-save-settings>Speichern</button></section>`}

function modal(html){const m=document.createElement('div');m.className='modal';m.innerHTML=`<div class="sheet">${html}</div>`;document.body.append(m);m.addEventListener('click',e=>{if(e.target===m||e.target.matches('[data-close]'))m.remove()});return m}
function trainingModal(p,date){p=p||{id:uid(),date:date||iso(new Date()),title:'',type:'Grundlage',duration:60,zone:'Z2',details:'',done:false,actual:{km:0,hm:0,duration:0,rpe:5,gear:false,note:''}};const m=modal(`<button class="icon-btn" data-close style="float:right">✕</button><h2>${data.plan.some(x=>x.id===p.id)?'Training bearbeiten':'Training anlegen'}</h2><div class="field"><label>Datum</label><input id="fDate" type="date" value="${p.date}"></div><div class="field"><label>Titel</label><input id="fTitle" value="${esc(p.title)}"></div><div class="row2"><div class="field"><label>Art</label><select id="fType">${['Grundlage','Sweetspot','Bergtraining','Lange Fahrt','Regeneration','Fußball','Kraft','Mobility','Ruhetag'].map(x=>`<option ${p.type===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>Dauer Min.</label><input id="fDuration" type="number" value="${p.duration||0}"></div></div><div class="field"><label>Zone / Intensität</label><input id="fZone" value="${esc(p.zone||'')}"></div><div class="field"><label>Details</label><textarea id="fDetails">${esc(p.details||'')}</textarea></div><button class="btn" id="saveTraining">Speichern</button>`);m.querySelector('#saveTraining').onclick=()=>{const item={...p,date:m.querySelector('#fDate').value,title:m.querySelector('#fTitle').value.trim(),type:m.querySelector('#fType').value,duration:+m.querySelector('#fDuration').value||0,zone:m.querySelector('#fZone').value,details:m.querySelector('#fDetails').value};if(!item.title)return toast('Bitte Titel eingeben');data.plan=data.plan.filter(x=>x.id!==item.id&&x.date!==item.date);data.plan.push(item);data.plan.sort((a,b)=>a.date.localeCompare(b.date));m.remove();save('Training gespeichert')}}
function completeModal(p){const a=p.actual||{};const m=modal(`<button class="icon-btn" data-close style="float:right">✕</button><h2>${esc(p.title)} durchführen</h2><p>${fmt(p.date)}</p><div class="row2"><div class="field"><label>Kilometer</label><input id="aKm" type="number" step="0.1" value="${a.km||0}"></div><div class="field"><label>Höhenmeter</label><input id="aHm" type="number" value="${a.hm||0}"></div></div><div class="row2"><div class="field"><label>Tatsächliche Dauer</label><input id="aDur" type="number" value="${a.duration||p.duration||0}"></div><div class="field"><label>RPE 1–10</label><input id="aRpe" type="number" min="1" max="10" value="${a.rpe||5}"></div></div><div class="field"><label>Notiz</label><textarea id="aNote">${esc(a.note||'')}</textarea></div><button class="btn" id="saveActual">Als erledigt speichern</button><button class="btn secondary" id="undoActual" style="margin-top:10px">Erledigt zurücknehmen</button>`);m.querySelector('#saveActual').onclick=()=>{p.done=true;p.actual={...a,km:+m.querySelector('#aKm').value||0,hm:+m.querySelector('#aHm').value||0,duration:+m.querySelector('#aDur').value||0,rpe:+m.querySelector('#aRpe').value||5,note:m.querySelector('#aNote').value};m.remove();save('Ergebnis gespeichert')};m.querySelector('#undoActual').onclick=()=>{p.done=false;m.remove();save('Status zurückgesetzt')}}
function tourModal(){const m=modal(`<button class="icon-btn" data-close style="float:right">✕</button><h2>Neue Tour</h2><div class="field"><label>Name</label><input id="tourName" placeholder="Tour de l’Ain"></div><div class="field"><label>Land</label><input id="tourCountry" placeholder="Frankreich"></div><button class="btn" id="saveTour">Tour erstellen</button>`);m.querySelector('#saveTour').onclick=()=>{const t={id:uid(),name:m.querySelector('#tourName').value.trim(),country:m.querySelector('#tourCountry').value.trim(),riderIds:[],stages:[]};if(!t.name)return toast('Name fehlt');data.tours.push(t);data.activeTourId=t.id;m.remove();save('Tour erstellt')}}
function riderModal(r,assign=true){r=r||{id:uid(),name:'',nation:'',role:'helfer',overall:70};const m=modal(`<button class="icon-btn" data-close style="float:right">✕</button><h2>Fahrer</h2><div class="field"><label>Name</label><input id="rName" value="${esc(r.name)}"></div><div class="row2"><div class="field"><label>Nationalität</label><input id="rNation" value="${esc(r.nation||'')}"></div><div class="field"><label>Rolle</label><select id="rRole">${Object.keys(roleLabel).map(x=>`<option value="${x}" ${r.role===x?'selected':''}>${roleLabel[x]}</option>`).join('')}</select></div></div><div class="field"><label>Gesamtstärke</label><input id="rOverall" type="number" min="1" max="99" value="${r.overall||70}"></div><button class="btn" id="saveRider">Speichern</button>`);m.querySelector('#saveRider').onclick=()=>{r.name=m.querySelector('#rName').value.trim();r.nation=m.querySelector('#rNation').value.trim();r.role=m.querySelector('#rRole').value;r.overall=+m.querySelector('#rOverall').value||70;if(!r.name)return toast('Name fehlt');if(!data.riderPool.some(x=>x.id===r.id))data.riderPool.push(r);const t=activeTour();if(assign&&t&&!t.riderIds.includes(r.id))t.riderIds.push(r.id);m.remove();save('Fahrer gespeichert')}}
function poolModal(){const t=activeTour();const m=modal(`<button class="icon-btn" data-close style="float:right">✕</button><h2>Globaler Fahrerpool</h2><div class="rider-grid">${data.riderPool.map(r=>`<div class="rider"><span class="role ${r.role}">${roleLabel[r.role]}</span><h4>${esc(r.name)}</h4><small>${esc(r.nation)}</small><div class="day-actions"><button class="icon-btn" data-pool-assign="${r.id}">${t?.riderIds?.includes(r.id)?'Zugeordnet':'Zur Tour'}</button></div></div>`).join('')||'<div class="empty">Noch leer</div>'}</div><button class="btn" data-pool-new>Neuen Fahrer anlegen</button>`);m.addEventListener('click',e=>{const id=e.target.dataset.poolAssign;if(id&&t){if(t.riderIds.includes(id))t.riderIds=t.riderIds.filter(x=>x!==id);else t.riderIds.push(id);m.remove();save('Tour-Kader aktualisiert')}if(e.target.matches('[data-pool-new]')){m.remove();riderModal(null,false)}})}
function stageModal(){const t=activeTour();if(!t)return;const m=modal(`<button class="icon-btn" data-close style="float:right">✕</button><h2>Etappe erstellen</h2><div class="row2"><div class="field"><label>Nummer</label><input id="sNum" type="number" value="${(t.stages?.length||0)+1}"></div><div class="field"><label>Typ</label><select id="sType"><option>Sprint</option><option>Hügel</option><option>Berg</option><option>Zeitfahren</option></select></div></div><div class="row2"><div class="field"><label>Start</label><input id="sStart"></div><div class="field"><label>Ziel</label><input id="sFinish"></div></div><div class="row2"><div class="field"><label>Kilometer</label><input id="sKm" type="number"></div><div class="field"><label>Höhenmeter</label><input id="sHm" type="number"></div></div><button class="btn" id="saveStage">Speichern</button>`);m.querySelector('#saveStage').onclick=()=>{t.stages=t.stages||[];t.stages.push({id:uid(),number:+m.querySelector('#sNum').value||1,type:m.querySelector('#sType').value,start:m.querySelector('#sStart').value,finish:m.querySelector('#sFinish').value,km:+m.querySelector('#sKm').value||0,hm:+m.querySelector('#sHm').value||0,results:[]});m.remove();save('Etappe erstellt')}}
function resultModal(stage){const t=activeTour(),riders=(t.riderIds||[]).map(id=>data.riderPool.find(r=>r.id===id)).filter(Boolean);const m=modal(`<button class="icon-btn" data-close style="float:right">✕</button><h2>Etappe ${stage.number} – Ergebnis</h2><div id="resultList">${(stage.results||[]).map((x,i)=>resultRow(x,i,riders)).join('')}</div><button class="btn secondary" id="addResult">+ Fahrer</button><button class="btn" id="saveResults" style="margin-top:10px">Klassement speichern</button><button class="btn danger" id="clearResults" style="margin-top:10px">Alles löschen</button>`);const list=m.querySelector('#resultList');m.querySelector('#addResult').onclick=()=>list.insertAdjacentHTML('beforeend',resultRow({},list.children.length,riders));m.querySelector('#saveResults').onclick=()=>{stage.results=[...list.querySelectorAll('.resultRow')].map(row=>({riderId:row.querySelector('.rr').value,seconds:+row.querySelector('.rt').value||0,sprint:+row.querySelector('.rs').value||0,mountain:+row.querySelector('.rm').value||0})).filter(x=>x.riderId);m.remove();save('Klassement gespeichert')};m.querySelector('#clearResults').onclick=()=>{stage.results=[];m.remove();save('Ergebnisse gelöscht')}}
function resultRow(x,i,riders){return `<div class="resultRow stage"><b>Platz ${i+1}</b><div class="field"><select class="rr"><option value="">Fahrer wählen</option>${riders.map(r=>`<option value="${r.id}" ${x.riderId===r.id?'selected':''}>${esc(r.name)} · ${roleLabel[r.role]}</option>`).join('')}</select></div><div class="row2"><input class="rt" type="number" placeholder="Zeit/Rückstand s" value="${x.seconds||0}"><input class="rs" type="number" placeholder="Sprintpunkte" value="${x.sprint||0}"></div><input class="rm" type="number" placeholder="Bergpunkte" value="${x.mountain||0}" style="width:100%;margin-top:8px"></div>`}

function bind(){document.addEventListener('click',globalClick,{once:true,capture:true});if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js').catch(()=>{})}
function globalClick(e){const t=e.target.closest('button,[data-toggle-card],[data-month-day]');if(!t)return bind();if(t.dataset.view){view=t.dataset.view;render();return}if(t.dataset.goTraining!==undefined){view='training';render();return}if(t.dataset.mode){trainingMode=t.dataset.mode;render();return}if(t.dataset.shiftWeek){weekStart=addDays(weekStart,+t.dataset.shiftWeek);render();return}if(t.dataset.shiftMonth){const d=new Date(monthCursor+'-01T12:00:00');d.setMonth(d.getMonth()+(+t.dataset.shiftMonth));monthCursor=iso(d).slice(0,7);render();return}if(t.dataset.monthDay){const p=data.plan.find(x=>x.date===t.dataset.monthDay);p?trainingModal(p):trainingModal(null,t.dataset.monthDay);return}if(t.dataset.addTraining!==undefined){trainingModal(null,t.dataset.date);return}if(t.dataset.toggleCard){document.querySelector(`[data-card="${t.dataset.toggleCard}"]`)?.classList.toggle('open');bind();return}if(t.dataset.editTraining){trainingModal(data.plan.find(x=>x.id===t.dataset.editTraining));return}if(t.dataset.complete){completeModal(data.plan.find(x=>x.id===t.dataset.complete));return}if(t.dataset.deleteTraining){data.plan=data.plan.filter(x=>x.id!==t.dataset.deleteTraining);save('Training gelöscht');return}if(t.dataset.newTour!==undefined){tourModal();return}if(t.dataset.selectTour){data.activeTourId=t.dataset.selectTour;save();return}if(t.dataset.tourSection){const at=activeTour();$('#tourSection').innerHTML=t.dataset.tourSection==='stages'?stageSection(at):t.dataset.tourSection==='standings'?standings(at):tourDetail(at);bind();return}if(t.dataset.addRider!==undefined){riderModal();return}if(t.dataset.managePool!==undefined){poolModal();return}if(t.dataset.editRider){riderModal(data.riderPool.find(x=>x.id===t.dataset.editRider));return}if(t.dataset.removeRider){const at=activeTour();at.riderIds=at.riderIds.filter(x=>x!==t.dataset.removeRider);save('Fahrer entfernt');return}if(t.dataset.newStage!==undefined){stageModal();return}if(t.dataset.stageResult){const s=activeTour().stages.find(x=>x.id===t.dataset.stageResult);resultModal(s);return}if(t.dataset.deleteStage){const at=activeTour();at.stages=at.stages.filter(x=>x.id!==t.dataset.deleteStage);save('Etappe gelöscht');return}if(t.dataset.export!==undefined){exportBackup();return}if(t.dataset.import!==undefined){importBackup();return}if(t.dataset.restore!==undefined){restoreSnapshot();return}if(t.dataset.saveSettings!==undefined){data.profile.monthlyGoal=+$('#monthlyGoal').value||500;save('Einstellungen gespeichert');return}bind()}
function exportBackup(){const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`projekt-nizza-backup-${iso(new Date())}.json`;a.click();data.profile.lastBackup=new Date().toISOString();save('Backup erstellt')}
function importBackup(){const i=document.createElement('input');i.type='file';i.accept='.json';i.onchange=()=>{const r=new FileReader();r.onload=()=>{try{data=normalize(JSON.parse(r.result));save('Backup wiederhergestellt')}catch{toast('Backup ungültig')}};r.readAsText(i.files[0])};i.click()}
function restoreSnapshot(){try{const a=JSON.parse(localStorage.getItem('projektNizzaSnapshots')||'[]');if(!a.length)return toast('Kein Snapshot vorhanden');data=normalize(a[0].data);save('Snapshot wiederhergestellt')}catch{toast('Wiederherstellung fehlgeschlagen')}}

(async()=>{const local=migrate(),db=await dbGet();data=normalize(db&&JSON.stringify(db).length>JSON.stringify(local).length?db:local);localStorage.setItem(KEY,JSON.stringify(data));render()})();
